### ISSUE TITLE
作用在viewgroup时报这个错（adapter中最外层relativelayout）

### ISSUE THREAD

**Issue by LambdaV5** [MagicMashRoom/SuperShadow#1]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.ViewGroup.indexOfChild(android.view.View)' on a null object reference
                                                                        at com.ldfeng.shadow.wrap.WrapRenderer.prepareLayout(WrapRenderer.java:42)
                                                                        at com.ldfeng.shadow.wrap.WrapRenderer.makeShadow(WrapRenderer.java:311)
                                                                        at com.ldfeng.shadow.SuperShadow.make(SuperShadow.java:55)
                                                                        at com.ldfeng.shadow.SuperShadow$Builder.action(SuperShadow.java:230)

**Comment by MagicMashRoom** [comment]
你是一运行就报错吗？

**Comment by MagicMashRoom** [comment]
你的要加阴影的view是不是没有父view

**Comment by MagicMashRoom** [comment]
如果你是在adapter中使用的话 
View date = LayoutInflater.from(context).inflate(R.layout.item_syllabus_date, parent, false);
                return new DateViewHolder(date);
这句话最好inflate的最后一个参数是TRUE

**Comment by LambdaV5** [comment]
嗯，这也是一种方式，不过你还是判断一下比较好

**Comment by cryshy** [comment]
在adapter里面，设置为的inflate（）方法的最后一个参数设置为true还是会报错
